Repository Hackathon2023springAteam/estate, pull requests merged in 2023-05, with the labels that each got.

#15 templates htmlファイル作成 #8 Feature/#8
  django/RealEstate360/urls.py
  django/RealEstate360/views.py
  django/estate/urls.py
  django/templates/detail.html
  django/templates/edit.html
  django/templates/lists.html
  django/templates/view_propertyinfos.html
Labels: Frontend

#25 Feature/#24/tanaka
  django/RealEstate360/forms.py
  django/RealEstate360/views.py
  django/templates/create.html
  django/templates/list.html
Labels: Frontend, Backend

#23 change redirect from list to detail
  django/RealEstate360/views.py
Labels: Frontend, Backend

#28 Feature/24/tanaka
  django/RealEstate360/models.py
  django/RealEstate360/views.py
  django/templates/create.html
Labels: Frontend, Backend

#30 ログイン画面UI作成
  django/RealEstate360/static/css/login.css
  django/templates/login.html
Labels: Frontend

#34 都道府県・市町村・町域のAPIを物件登録に導入する。
  django/templates/base.html
  django/templates/create.html
Labels: Frontend, Backend

#39 basicinfomationのaddressを修正、管理番号を自動採番
  django/RealEstate360/migrations/0002_auto_20230519_1101.py
  django/RealEstate360/migrations/0003_alter_basicinformation_control_number.py
  django/RealEstate360/models.py
  django/templates/create.html
Labels: Frontend, Backend

#40 新規登録画面UI実装　forms.pyを使用した実装 Feature/#33
  django/RealEstate360/migrations/0002_alter_buildinginformation_type_of_rights.py
  django/RealEstate360/static/css/base.css
  django/RealEstate360/static/css/create.css
  django/RealEstate360/static/css/lists.css
  django/templates/base.html
  django/templates/create.html
  nginx/static/css/base.css
  nginx/static/css/lists.css
Labels: Frontend

#47 一覧画面項目の入れ替え、list.css追加
  django/RealEstate360/static/css/list.css
  django/RealEstate360/static/css/lists.css
  django/templates/list.html
Labels: Frontend

#55 検索フォームUIの修正 Feature/#52
  django/RealEstate360/static/css/list.css
  django/templates/base.html
  django/templates/list.html
Labels: Frontend

#57 各inputをselectにできるものは変更(Feature/#53/tanaka)
  .gitignore
  django/RealEstate360/forms.py
  django/RealEstate360/migrations/0001_initial.py
  django/RealEstate360/migrations/0002_auto_20230519_1101.py
  django/RealEstate360/migrations/0003_alter_basicinformation_control_number.py
  django/RealEstate360/models.py
  django/RealEstate360/views.py
  django/templates/create.html
  django/templates/edit.html
Labels: Frontend, Backend

#58 登録情報詳細画面のボタンデザイン変更 Feature/#50
  django/RealEstate360/static/css/detail.css
  django/RealEstate360/static/img/icon_delete-hover.svg
  django/RealEstate360/static/img/icon_delete.svg
  django/templates/detail.html
Labels: Frontend

#61 create.htmlとedit.htmlにエラー表示を実装。(Feature/#60/tanaka)
  django/RealEstate360/forms.py
  django/RealEstate360/models.py
  django/RealEstate360/views.py
  django/templates/create.html
  django/templates/edit.html
Labels: Frontend, Backend

#63 都道府県のselectで住所地に入力 (Feature/#62/tanaka)
  django/templates/create.html
  django/templates/edit.html
Labels: Frontend, Backend

#68 login.htmlをホームページに #67
  django/RealEstate360/urls.py
Labels: Backend

#70 数値入力のstepをカーソル位置で可変 (Feature/#69/tanaka)
  django/RealEstate360/forms.py
  django/templates/create.html
  django/templates/edit.html
Labels: Frontend, Backend

#72 物件一覧ページの住所検索フォーム修正 #71
  django/RealEstate360/static/css/create.css
  django/RealEstate360/static/css/detail.css
  django/RealEstate360/static/css/edit.css
  django/RealEstate360/static/css/list.css
  django/templates/create.html
  django/templates/edit.html
  django/templates/list.html
Labels: Frontend
